### PR TITLE
Adding the ability to skpi CI when updating docs [skip-ci]

### PR DESCRIPTION
**Pull request by juanmanuelramallo**
- Added an if attribute to our ci.yml configuration

### CODE REVIEW

**Comment by santib** [comment]
@juanmanuelramallo I think we need to change github config so that checks don't appear as required for this kind of PRs?

**Comment by juanmanuelramallo** [comment]
> @juanmanuelramallo I think we need to change github config so that checks don't appear as required for this kind of PRs?

I haven't found how to do that, do you have any clue?

**Comment by santib** [comment]
> > @juanmanuelramallo I think we need to change github config so that checks don't appear as required for this kind of PRs?
> 
> I haven't found how to do that, do you have any clue?

no idea, maybe the status checks shouldn't be required (?)

**Comment by juanmanuelramallo** [comment]
@santib hmmm I'm not sure we can configure the checks to be optional for these commits and required for every other one. I believe that's not possible with Github's protected branches.

**Comment by santib** [comment]
> @santib hmmm I'm not sure we can configure the checks to be optional for these commits and required for every other one. I believe that's not possible with Github's protected branches.

I was saying that maybe we need to do it for all the PRs. Not sure if that's how rails achieves it

**Comment by juanmanuelramallo** [comment]
@santib gotcha, I'm gonna leave them as not required globally then, makes sense.

**Pull request merged**
